In [9]:
import numpy as np

In [10]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c= np.dot(a,b)
toc = time.time()
print(c)
print('Vectorized Version: '+ str(1000*(toc-tic))+"ms")


c= 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
print(c)
print('Time taken in case of for loop is: '+str(1000*(toc-tic))+"ms")

249799.65803791978
Vectorized Version: 2.7649402618408203ms
249799.65803792383
Time taken in case of for loop is: 398.65851402282715ms


In [11]:
a = np.random.randn(5)
a

array([-0.40196009,  1.26749204,  0.29795688, -0.38961887,  0.67271356])

In [12]:
a.shape

(5,)

In [13]:
a.T #Transpose

array([-0.40196009,  1.26749204,  0.29795688, -0.38961887,  0.67271356])

In [14]:
np.dot(a, a.T)

2.461232685415169

In [17]:
b = np.random.rand(5,1)

In [18]:
b

array([[0.12404213],
       [0.57635699],
       [0.26997355],
       [0.0323869 ],
       [0.3259137 ]])

In [19]:
b.T

array([[0.12404213, 0.57635699, 0.26997355, 0.0323869 , 0.3259137 ]])

In [20]:
np.dot(b, b.T)

array([[0.01538645, 0.07149255, 0.03348809, 0.00401734, 0.04042703],
       [0.07149255, 0.33218738, 0.15560114, 0.01866641, 0.18784264],
       [0.03348809, 0.15560114, 0.07288572, 0.00874361, 0.08798808],
       [0.00401734, 0.01866641, 0.00874361, 0.00104891, 0.01055533],
       [0.04042703, 0.18784264, 0.08798808, 0.01055533, 0.10621974]])