Some most fundamentals concepts of tensors.
+ Intro to tensors
+ Getting informations from tensors
+ Manipulating tensors
+ Tansors and NumPy
+ using @tf.function
+ Using GPUs and TPUs
+ Excercise !!!!

### Intro to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Crearting tensors using tf.constant()

scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Check the number od dimensions

scaler.ndim

2

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix

matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix

another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim


3